# Generated by Django 5.2.14 on 2026-05-22 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('dest_name', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('low', '하'), ('medium', '중'), ('high', '상')], default='low', max_length=10)),
                ('target_minutes', models.IntegerField()),
                ('estimated_minutes', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('risk_count', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
