# Generated by Django 5.2.15 on 2026-06-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_practicecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OraiZone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedPracticeCourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
                ('practice_type', models.CharField(choices=[('beginner', '처음 운전'), ('lane_keep', '차선 유지'), ('right_turn', '우회전'), ('left_turn', '좌회전'), ('u_turn', '유턴'), ('lane_change', '차선 변경'), ('parking', '주차장 진입')], max_length=30)),
                ('level', models.CharField(choices=[('beginner', '입문'), ('adapt', '적응'), ('challenge', '도전')], default='beginner', max_length=20)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('base_minutes', models.IntegerField()),
                ('distance_km', models.FloatField(default=0)),
                ('straight_ratio', models.IntegerField(default=0)),
                ('right_turn_count', models.IntegerField(default=0)),
                ('left_turn_count', models.IntegerField(default=0)),
                ('u_turn_count', models.IntegerField(default=0)),
                ('lane_change_count', models.IntegerField(default=0)),
                ('speed_bump_count', models.IntegerField(default=0)),
                ('school_zone_count', models.IntegerField(default=0)),
                ('accident_hotspot_count', models.IntegerField(default=0)),
                ('complex_intersection_count', models.IntegerField(default=0)),
                ('positive_ratio', models.IntegerField(default=80)),
                ('reward_text', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.oraizone')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('good', '괜찮았어요'), ('bad', '어려웠어요')], max_length=10)),
                ('difficult_reasons', models.JSONField(blank=True, default=list)),
                ('actual_minutes', models.IntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.verifiedpracticecourse')),
            ],
        ),
    ]
