# Generated by Django 5.2.15 on 2026-06-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_oraizone_verifiedpracticecourse_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='category',
            field=models.CharField(default='tip', max_length=30),
        ),
        migrations.CreateModel(
            name='PracticeDriveRecord',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', '주행 중'), ('completed', '완료'), ('cancelled', '취소')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.IntegerField(blank=True, null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_records', to='api.verifiedpracticecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_drives', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='drive_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.practicedriverecord'),
        ),
    ]
